### ISSUE TITLE
false return value

### ISSUE THREAD

**Issue by srhinow** [legito/api-wrapper#3]
I use this:
```
        $LegitoApi = new Legito($objType->apiKey, $objType->privateKey);
        $LegitoWrapper = $LegitoApi->getWrapper();
        $docList = $LegitoWrapper->getDocumentRecord();
```
then the following error occurs
```
Type error: Return value of Legito\Api\Wrapper\V1\Resource\DocumentRecord::getDocumentRecord() must be of the type array, object returned
```
If I do this in the api-wrapper Resource/DocumentRecord.php`dump($result->response); die();` have it output, it is also an object with status and code.
```
DocumentRecord.php on line 37:
"""
{\n
    "code": 200,\n
    "status": "OK"\n
}
"""
```
but not the List of documents?!

**Comment by srhinow** [comment]
thats return as object because the json -> json_decode() function needed the second parameter true if its return as array instead of as object

source: restclient.php -> decode_response()

php-docu: https://www.php.net/manual/en/function.json-decode.php

**Comment by srhinow** [comment]
but why does the API only return a '200' and an 'ok' instead of the list of all documents?

**Comment by marekskopal** [comment]
Hi Sven, 

I tried several requets with `getDocumentRecord();` method and all returns list of document records corretly. So I cannot reproduce your issue.

However we deployed some patches to API on legito.com server yesterday, so maybe there was also fix for this problem.

Please try it again and write me if it help or issue still exists.

**Comment by srhinow** [comment]
that is still the same problem.
object is not an array (hint json_decode($json,**true**))
![Bildschirmfoto zu 2020-06-24 09-16-51](https://user-images.githubusercontent.com/741418/85513916-c5e8ab80-b5fb-11ea-845c-19d803bd49ab.png)
![Bildschirmfoto zu 2020-06-24 09-28-54](https://user-images.githubusercontent.com/741418/85515234-2debc180-b5fd-11ea-89f0-e2f5990b6cbf.png)

**Comment by srhinow** [comment]
and the return is still determined only by the code and status.
![Bildschirmfoto zu 2020-06-24 09-20-27](https://user-images.githubusercontent.com/741418/85514218-1a8c2680-b5fc-11ea-9042-2baee82014a2.png)

I currently call it up like this:
```
        $LegitoApi =  (new Legito($objType->apiKey, $objType->privateKey))->getWrapper();
        $docList = $LegitoApi->getDocumentRecord();
```
$docList should contain the array of documents or do I have to access it any other way?

**Comment by srhinow** [comment]
I previously updated to the latest version 2.0.1

**Comment by marekskopal** [comment]
Hi Sven,

I checks response in yours workspace and there is error on server side of our API if you has empty list of document records. Currenty we worked on fix and will be deploy about next week.

If you create (or restore some of deleted) document record API will work fine.

**Comment by basistom** [comment]
So as I understand you now, we have to create a document based on a template to get the template-list? 
I would expect to get the template-list instead of the document-list. Can you explain me the behavior for a better understanding of the function please?

**Comment by srhinow** [comment]
When i try delete document what i create short before, happened this error as response:

`Document record with code "l4LdoqTIUJgdkWHxTzuRcNYRuKVtDHLE6HchEcIa" was not found.`

this is my code to create a document, save this in system and remove it in legito-system.
```php
        // Create instance
        $legitoApi = (new \Legito\Api\Legito($this->params['apiKey'], $this->params['privateKey']))->getWrapper();

        //Token-Daten als Array holen
        $data = $this->getData();

        //Daten an Legito übertragen
        $putReturn = $legitoApi->putDocumentVersionData($this->params['code'],$data);

        //Datei generieren
        // 
        $filesReturn = $legitoApi->getDocumentVersionDownload($putReturn->code,$this->params['format'], $this->params['documentId'], $this->params['templateId']);

        if(!is_array($filesReturn)) {
            Message::addError($GLOBALS['TL_LANG']['tl_spree_document_configurator']['generator_message']['generate_file_failed']);
            return false;
        }

        //Dateien generieren
        $arrUuid = [];
        foreach($filesReturn as $file) {

            $fileModel = $this->generateFile($file->data);

            if($fileModel) {
                //Dateien in DB speichern
                $this->saveFile($fileModel);
            };
        }

        //generierte Datei in Legito wieder loeschen
        try {
            $legitoApi->deleteDocumentRecord($putReturn->code);
        } catch (\Exception $e) {
            $msg = sprintf(
                $GLOBALS['TL_LANG']['tl_spree_document_configurator']['generator_message']['legito_file_delete_failed'],
                $e->getMessage()
            );
            Helper::createErrorLogEntry($msg);
            Message::addError($msg);
        }

        return true;
```
what is failure?

**Comment by marekskopal** [comment]
Hi Sven,

there are two separate entities in Legito

- Document Record
- Document Version

Document Record is pack of Document Versions.

metod `putDocumentVersionData()` updates Document Version entity, but method `deleteDocumentRecord()` deletes Document Record entity and codes for these entities are not the same. 

Currenty there isn't simple way how to get `code` parameter for Document Record from Document Version. We will add necessary attributes in next version of API which will be deploy next month (current version will be still supported).
